const s = Symbol("s");
const t = Symbol("t");
const a: any = [1,2,3];
a.foo = 40;
a[s] = 10;
a[t] = 20;
console.log("initial", a.foo, a[s], a[t], Object.getOwnPropertySymbols(a).map(x => x.description).join(","));
for (let i=0;i<100;i++) a.push(i);
console.log("grown", a.length, a.foo, a[s], a[t]);
delete a[s];
a[s] = 30;
console.log("order", Object.getOwnPropertySymbols(a).map(x => x.description).join(","));
let gets = 0;
Object.defineProperty(a, t, {get() { gets++; return this.foo + 2; }, configurable: true});
console.log("accessor", a[t], gets);
Object.defineProperty(a, t, {value: 99, writable: true, configurable: true});
console.log("data", a[t], gets, Reflect.ownKeys(a).filter(x => typeof x === "symbol").map(x => x.description).join(","));
delete a.foo;
console.log("deleted-name", a.foo, a[s]);
const parent: any = [];
parent[s] = 5;
const child: any = [1,2];
Object.setPrototypeOf(child, parent);
console.log("inherited-symbol", child[s]);
const iterable: any = [1,2,3];
let factories = 0;
Object.defineProperty(iterable, Symbol.iterator, {get() { factories++; return function() { let n=0; const self=this; return {next() { return {value: self[n++], done: n>self.length}; }}; }; }, configurable:true});
console.log("iterator-getter", [...iterable].join(","), factories);
for (let i=0; i<40; i++) a["name"+i] = i;
console.log("names-grown", a.name39, a[s], a[t]);
const values = Array.prototype.values;
console.log("values-function", values === Array.prototype[Symbol.iterator], values.name, values.length, Object.getOwnPropertyDescriptor(values, "length")!.writable);
