// Auto-generated by scripts/gen_parity_tests.py from docs/runtime-parity.md.
// Module: node:dns/promises
// This file is a byte-for-byte parity test against `node --experimental-strip-types`.
// Edit the TODO lines below to exercise each API; rerun
// `./run_parity_tests.sh --filter test_parity_dns_promises` to verify.

import * as dns_promises from "node:dns/promises";
import * as dns from "node:dns";


// ── Functions ──
// Non-deterministic resolution APIs — only probe types/presence, never call externally.
console.log("typeof dnsPromises.lookup:", typeof dns_promises.lookup);
// PERRY-SKIP: dnsPromises.lookupService — requires live reverse lookup.
console.log("typeof dnsPromises.lookupService:", typeof dns_promises.lookupService);
console.log("typeof dnsPromises.resolve:", typeof dns_promises.resolve);
console.log("typeof dnsPromises.resolve4:", typeof dns_promises.resolve4);
console.log("typeof dnsPromises.resolve6:", typeof dns_promises.resolve6);
console.log("typeof dnsPromises.resolveAny:", typeof dns_promises.resolveAny);
console.log("typeof dnsPromises.resolveCaa:", typeof dns_promises.resolveCaa);
console.log("typeof dnsPromises.resolveCname:", typeof dns_promises.resolveCname);
console.log("typeof dnsPromises.resolveMx:", typeof dns_promises.resolveMx);
console.log("typeof dnsPromises.resolveNaptr:", typeof dns_promises.resolveNaptr);
console.log("typeof dnsPromises.resolveNs:", typeof dns_promises.resolveNs);
console.log("typeof dnsPromises.resolvePtr:", typeof dns_promises.resolvePtr);
console.log("typeof dnsPromises.resolveSoa:", typeof dns_promises.resolveSoa);
console.log("typeof dnsPromises.resolveSrv:", typeof dns_promises.resolveSrv);
console.log("typeof dnsPromises.resolveTlsa:", typeof dns_promises.resolveTlsa);
console.log("typeof dnsPromises.resolveTxt:", typeof dns_promises.resolveTxt);
console.log("typeof dnsPromises.reverse:", typeof dns_promises.reverse);
try {
  const originalServers = dns_promises.getServers();
  const originalCallbackServers = dns.getServers();
  console.log("dnsPromises.getServers isArray:", Array.isArray(originalServers));
  console.log("dnsPromises.getServers length typeof:", typeof originalServers.length);
  dns_promises.setServers(["1.1.1.1", "[2001:4860:4860::8888]:1053"]);
  console.log("dnsPromises.setServers roundtrip:", dns_promises.getServers().join("|"));
  console.log(
    "dns callback servers unchanged:",
    dns.getServers().join("|") === originalCallbackServers.join("|"),
  );
  dns.setServers(["8.8.8.8", "::1"]);
  console.log("dns callback set leaves dnsPromises:", dns_promises.getServers().join("|"));
  try {
    dns_promises.setServers(["not ip"]);
  } catch (e) {
    console.log("dnsPromises.setServers invalid ip:", (e as Error).name, (e as any).code);
  }
  try {
    dns_promises.setServers("1.1.1.1" as any);
  } catch (e) {
    console.log("dnsPromises.setServers non-array:", (e as Error).name, (e as any).code);
  }
  try {
    dns_promises.setServers([1] as any);
  } catch (e) {
    console.log("dnsPromises.setServers non-string:", (e as Error).name, (e as any).code);
  }
  console.log("dnsPromises.setServers invalid keeps previous:", dns_promises.getServers().join("|"));
  dns_promises.setServers(originalServers);
  console.log(
    "dnsPromises.setServers restored:",
    dns_promises.getServers().join("|") === originalServers.join("|"),
  );
  dns.setServers(originalCallbackServers);
  console.log(
    "dns callback setServers restored:",
    dns.getServers().join("|") === originalCallbackServers.join("|"),
  );
} catch (e) {
  console.log("dnsPromises.getServers/setServers error:", (e as Error).message);
}
try {
  const originalOrder = dns_promises.getDefaultResultOrder();
  dns_promises.setDefaultResultOrder("verbatim");
  console.log(
    "dnsPromises.setDefaultResultOrder('verbatim'):",
    dns_promises.getDefaultResultOrder(),
  );
  dns_promises.setDefaultResultOrder("ipv4first");
  console.log(
    "dnsPromises.setDefaultResultOrder('ipv4first'):",
    dns_promises.getDefaultResultOrder(),
  );
  dns_promises.setDefaultResultOrder("ipv6first");
  console.log(
    "dnsPromises.setDefaultResultOrder('ipv6first'):",
    dns_promises.getDefaultResultOrder(),
  );
  console.log("dns callback shared result order:", dns.getDefaultResultOrder());
  try {
    dns_promises.setDefaultResultOrder("bad-order" as any);
  } catch (e) {
    console.log(
      "dnsPromises.setDefaultResultOrder invalid:",
      (e as Error).name,
      (e as any).code,
    );
  }
  console.log(
    "dnsPromises.setDefaultResultOrder invalid keeps previous:",
    dns_promises.getDefaultResultOrder(),
  );
  dns_promises.setDefaultResultOrder(originalOrder as any);
  console.log(
    "dnsPromises.setDefaultResultOrder restored:",
    dns_promises.getDefaultResultOrder() === originalOrder,
  );
} catch (e) {
  console.log("dnsPromises.setDefaultResultOrder error:", (e as Error).message);
}
console.log("dnsPromises.getDefaultResultOrder():", dns_promises.getDefaultResultOrder());

// ── localhost lookup (deterministic) ──
async function probeLocalhost() {
  try {
    const r = await dns_promises.lookup("localhost");
    console.log("loopback:", r.address === "127.0.0.1" || r.address === "::1");
    console.log("loopback family typeof:", typeof r.family);
  } catch (e) {
    console.log("loopback error:", (e as Error).message);
  }
}
probeLocalhost();

// ── Classes ──
console.log("class dnsPromises.Resolver typeof:", typeof dns_promises.Resolver);
try {
  const originalServers = dns_promises.getServers();
  const r = new dns_promises.Resolver();
  const sibling = new dns_promises.Resolver();
  console.log("new dnsPromises.Resolver typeof:", typeof r);
  console.log("resolver.cancel typeof:", typeof r.cancel);
  console.log("resolver.setServers typeof:", typeof r.setServers);
  console.log("resolver.setLocalAddress typeof:", typeof (r as any).setLocalAddress);
  console.log("resolver.resolve typeof:", typeof r.resolve);
  console.log("resolver.resolve4 typeof:", typeof r.resolve4);
  console.log("resolver.resolve6 typeof:", typeof r.resolve6);
  console.log("resolver.resolveMx typeof:", typeof r.resolveMx);
  console.log("resolver.resolveTxt typeof:", typeof r.resolveTxt);
  console.log("resolver.reverse typeof:", typeof r.reverse);
  console.log("resolver.cancel returns undefined:", r.cancel() === undefined);
  const initialServers = r.getServers();
  console.log("resolver.initial getServers isArray:", Array.isArray(initialServers));
  console.log("resolver.initial getServers length typeof:", typeof initialServers.length);
  const siblingBefore = sibling.getServers().join("|");
  const moduleBefore = dns_promises.getServers().join("|");
  r.setServers(["1.0.0.1", "[::1]:5353"]);
  const rsrv = r.getServers();
  console.log("resolver.getServers isArray:", Array.isArray(rsrv));
  console.log("resolver.getServers roundtrip:", rsrv.join("|"));
  console.log("resolver.setServers leaves sibling:", sibling.getServers().join("|") === siblingBefore);
  console.log("resolver.setServers leaves dnsPromises:", dns_promises.getServers().join("|") === moduleBefore);
  try {
    r.setServers(["not ip"]);
  } catch (e) {
    console.log("resolver.setServers invalid ip:", (e as Error).name, (e as any).code);
  }
  console.log("resolver.setServers invalid keeps previous:", r.getServers().join("|"));
  dns_promises.setServers(originalServers);
} catch (e) {
  console.log("Resolver error:", (e as Error).message);
}

// Coverage: 0 auto-emitted, 22 TODO, 0 skip-listed.
