//! Feature parity rows for application-level surfaces:
//! lifecycle (App/Window), timers, menus, clipboard, dialogs,
//! keyboard shortcuts, and navigation stacks.
//!
//! Split out from `lib.rs` (issue followup to #1864) to keep that file
//! under the 2000-LOC limit while making this matrix easier to navigate.

use crate::{Category::*, Feature, S};

pub(crate) const ROWS: &[Feature] = &[
    // ── AppLifecycle ──────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_app_create",
        category: AppLifecycle,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_app_run",
        category: AppLifecycle,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_app_set_body",
        category: AppLifecycle,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_app_set_min_size",
        category: AppLifecycle,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_app_set_max_size",
        category: AppLifecycle,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_app_on_activate",
        category: AppLifecycle,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_app_on_terminate",
        category: AppLifecycle,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_window_create",
        category: AppLifecycle,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_window_set_body",
        category: AppLifecycle,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_window_show",
        category: AppLifecycle,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_window_close",
        category: AppLifecycle,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // ── Timer ─────────────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_app_set_timer",
        category: Timer,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // ── Menu ─────────────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_menu_create",
        category: Menu,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_menu_add_item",
        category: Menu,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_menu_add_item_with_shortcut",
        category: Menu,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_menu_add_separator",
        category: Menu,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_menu_add_submenu",
        category: Menu,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_menubar_create",
        category: Menu,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_menubar_add_menu",
        category: Menu,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_menubar_attach",
        category: Menu,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_menu_clear",
        category: Menu,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_menu_add_standard_action",
        category: Menu,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // ── Clipboard ────────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_clipboard_read",
        category: Clipboard,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_clipboard_write",
        category: Clipboard,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // ── Dialog ───────────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_open_file_dialog",
        category: Dialog,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_save_file_dialog",
        category: Dialog,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_alert",
        category: Dialog,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // ── Keyboard Shortcut ────────────────────────────────────────────────
    Feature {
        name: "perry_ui_add_keyboard_shortcut",
        category: KeyboardShortcut,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // ── Navigation ───────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_navstack_create",
        category: Navigation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_navigationstack_create"),
    },
    Feature {
        name: "perry_ui_navstack_push",
        category: Navigation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_navstack_pop",
        category: Navigation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
];
