//! Feature parity rows for the reactive state primitives.

use crate::{Category::*, Feature, S};

pub(crate) const ROWS: &[Feature] = &[
    // ── State System ─────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_state_create",
        category: StateSystem,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_state_get",
        category: StateSystem,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_state_set",
        category: StateSystem,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_state_on_change",
        category: StateSystem,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // ── State Bindings ───────────────────────────────────────────────────
    Feature {
        name: "perry_ui_state_bind_slider",
        category: StateBind,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_state_bind_text_numeric",
        category: StateBind,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_state_bind_text_template",
        category: StateBind,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_state_bind_text"),
    },
    Feature {
        name: "perry_ui_state_bind_textfield",
        category: StateBind,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_state_bind_toggle",
        category: StateBind,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_state_bind_visibility",
        category: StateBind,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
];
