//! Feature parity rows for visual styling: text, generic style props,
//! and Canvas drawing operations.

use crate::{Category::*, Feature, S};

pub(crate) const ROWS: &[Feature] = &[
    // ── Text Styling ─────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_text_set_string",
        category: TextStyling,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_text_set_color",
        category: TextStyling,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_set_foreground"),
    },
    Feature {
        name: "perry_ui_text_set_font_size",
        category: TextStyling,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_set_font_size"),
    },
    Feature {
        name: "perry_ui_text_set_font_weight",
        category: TextStyling,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_set_font_weight"),
    },
    Feature {
        name: "perry_ui_text_set_selectable",
        category: TextStyling,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_text_set_font_family",
        category: TextStyling,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_set_font_family"),
    },
    // ── Styling ──────────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_widget_set_background_color",
        category: Styling,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_set_background"),
    },
    Feature {
        name: "perry_ui_widget_set_background_gradient",
        category: Styling,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_widget_set_corner_radius",
        category: Styling,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_set_corner_radius"),
    },
    Feature {
        name: "perry_ui_widget_set_context_menu",
        category: Styling,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_widget_set_control_size",
        category: Styling,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_set_control_size"),
    },
    Feature {
        name: "perry_ui_widget_set_enabled",
        category: Styling,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_set_enabled"),
    },
    Feature {
        name: "perry_ui_widget_set_tooltip",
        category: Styling,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_set_tooltip"),
    },
    Feature {
        name: "perry_ui_set_widget_hidden",
        category: Styling,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // ── Canvas ───────────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_canvas_clear",
        category: Canvas,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_canvas_clear_rect"),
    },
    Feature {
        name: "perry_ui_canvas_begin_path",
        category: Canvas,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_canvas_move_to",
        category: Canvas,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_canvas_line_to",
        category: Canvas,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_canvas_stroke",
        category: Canvas,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_canvas_fill_gradient",
        category: Canvas,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
];
