use super::*;

pub(super) const DATES_ROWS: &[NativeModSig] = &[
    // ========== moment ==========
    // Same handle scheme as dayjs: the factory returns
    // f64::from_bits(handle) and instance methods take the handle as an
    // i64 first arg (the runtime signatures were converted from the old
    // `handle: f64` ABI, which was incompatible with the
    // has_receiver:true i64-first-arg dispatch — that's why only the
    // factory used to be wired and every instance method returned
    // undefined). Other-moment args (diff/isBefore/isAfter/isSame/
    // isBetween) pass NA_JSV — the raw f64 bits ARE the handle.
    NativeModSig {
        module: "moment",
        has_receiver: false,
        method: "default",
        class_filter: None,
        runtime: "js_moment_factory",
        args: &[NA_JSV],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: false,
        method: "moment",
        class_filter: None,
        runtime: "js_moment_factory",
        args: &[NA_JSV],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "format",
        class_filter: None,
        runtime: "js_moment_format",
        args: &[NA_STR],
        ret: NR_STR,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "toISOString",
        class_filter: None,
        runtime: "js_moment_to_iso_string",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "valueOf",
        class_filter: None,
        runtime: "js_moment_value_of",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "unix",
        class_filter: None,
        runtime: "js_moment_unix",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "year",
        class_filter: None,
        runtime: "js_moment_year",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "month",
        class_filter: None,
        runtime: "js_moment_month",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "date",
        class_filter: None,
        runtime: "js_moment_date",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "day",
        class_filter: None,
        runtime: "js_moment_day",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "hour",
        class_filter: None,
        runtime: "js_moment_hour",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "minute",
        class_filter: None,
        runtime: "js_moment_minute",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "second",
        class_filter: None,
        runtime: "js_moment_second",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "millisecond",
        class_filter: None,
        runtime: "js_moment_millisecond",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "add",
        class_filter: None,
        runtime: "js_moment_add",
        args: &[NA_F64, NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "subtract",
        class_filter: None,
        runtime: "js_moment_subtract",
        args: &[NA_F64, NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "startOf",
        class_filter: None,
        runtime: "js_moment_start_of",
        args: &[NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "endOf",
        class_filter: None,
        runtime: "js_moment_end_of",
        args: &[NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "diff",
        class_filter: None,
        runtime: "js_moment_diff",
        args: &[NA_JSV, NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "isBefore",
        class_filter: None,
        runtime: "js_moment_is_before",
        args: &[NA_JSV],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "isAfter",
        class_filter: None,
        runtime: "js_moment_is_after",
        args: &[NA_JSV],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "isSame",
        class_filter: None,
        runtime: "js_moment_is_same",
        args: &[NA_JSV, NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "isBetween",
        class_filter: None,
        runtime: "js_moment_is_between",
        args: &[NA_JSV, NA_JSV],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "isValid",
        class_filter: None,
        runtime: "js_moment_is_valid",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "clone",
        class_filter: None,
        runtime: "js_moment_clone",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "fromNow",
        class_filter: None,
        runtime: "js_moment_from_now",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "moment",
        has_receiver: true,
        method: "toDate",
        class_filter: None,
        runtime: "js_moment_to_date",
        args: &[],
        ret: NR_F64,
    },
];
