//! The static-id seeds (design step 4, §7.3): the mint adopts a requested
//! static id only on a by-facts miss, and a refusal (the id outside its band,
//! or already naming other facts) aborts: ids are assigned by content.
use super::*;
use crate::object::shapes::{is_shape_id, SHAPE_ID_BASE, STATIC_SHAPE_ID_END};

fn seed(requested: u32, names: &[&str]) -> u32 {
    let packed: Vec<u8> = names
        .iter()
        .flat_map(|n| n.bytes().chain(std::iter::once(0)))
        .collect();
    js_shape_seed_plain(
        requested,
        packed.as_ptr(),
        packed.len() as u32,
        names.len() as u32,
    )
}

fn is_carrier(id: u32) -> bool {
    shapes::test_shape_record_is_carrier(id)
}

#[test]
fn a_seed_mints_the_requested_id_and_every_later_mint_of_those_facts_resolves_to_it() {
    let requested = SHAPE_ID_BASE + 0x1234;
    let id = seed(requested, &["lt4s_a", "lt4s_b"]);
    assert_eq!(id, requested, "the seed must mint the requested static id");
    assert!(
        is_carrier(id),
        "a seeded record must carry RECORD_FLAG_EXTERNAL_CARRIER (never pruned)"
    );
    // The ordinary literal birth of the same key list (the canonical node,
    // count = live bound, proto 0) reaches the seeded record.
    let keys = unsafe { canonical_keys_for_names(&[b"lt4s_a", b"lt4s_b"]) };
    assert_eq!(shapes::shape_id_for_keys_ensure(keys.arr(), 2), requested);
    // A second seed of the same facts under another id finds the first.
    assert_eq!(
        seed(SHAPE_ID_BASE + 0x1235, &["lt4s_a", "lt4s_b"]),
        requested
    );
    assert!(
        shapes::shape_descriptor_by_id(SHAPE_ID_BASE + 0x1235).is_none(),
        "a by-facts hit must not mint the second requested id"
    );
}

/// Run `name` in a child test process with `SABOTAGE_ENV` set and require it
/// to abort with the mint's refusal message.
fn child_aborts_with_refusal(name: &str) {
    let out = std::process::Command::new(std::env::current_exe().expect("test binary"))
        .arg(name)
        .arg("--exact")
        .arg("--nocapture")
        .arg("--test-threads=1")
        .env(SABOTAGE_ENV, "1")
        .output()
        .expect("launch the sabotaged child");
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(!out.status.success(), "the refused static id did not abort");
    assert!(
        stderr.contains("was refused by the shape mint"),
        "the child died without the refusal message: {stderr}"
    );
}

const SABOTAGE_ENV: &str = "PERRY_TEST_PLAIN_STATIC_REFUSAL_CHILD";

/// Ids are assigned by content, so a static id already naming OTHER facts in
/// this agent is an invariant violation: the mint aborts rather than hand a
/// counter id to code whose immediates name the static one.
#[test]
fn a_static_id_already_naming_other_facts_aborts() {
    if std::env::var_os(SABOTAGE_ENV).is_none() {
        child_aborts_with_refusal(
            "object::static_shapes::tests::a_static_id_already_naming_other_facts_aborts",
        );
        return;
    }
    let requested = SHAPE_ID_BASE + 0x2345;
    assert_eq!(seed(requested, &["lt4d_x"]), requested);
    seed(requested, &["lt4d_y"]);
}

/// A requested id outside the static band is never generated by the driver;
/// the mint aborts on it (each bad id in its own child).
#[test]
fn a_requested_id_outside_the_static_band_aborts() {
    const BAD: [u32; 3] = [0x7000_0000, STATIC_SHAPE_ID_END, STATIC_SHAPE_ID_END + 5];
    match std::env::var(SABOTAGE_ENV) {
        Err(_) => {
            for i in 0..BAD.len() {
                let out = std::process::Command::new(std::env::current_exe().expect("test binary"))
                    .arg("object::static_shapes::tests::a_requested_id_outside_the_static_band_aborts")
                    .arg("--exact")
                    .arg("--nocapture")
                    .arg("--test-threads=1")
                    .env(SABOTAGE_ENV, i.to_string())
                    .output()
                    .expect("launch the sabotaged child");
                let stderr = String::from_utf8_lossy(&out.stderr);
                assert!(
                    !out.status.success(),
                    "out-of-band {:#x} did not abort",
                    BAD[i]
                );
                assert!(
                    stderr.contains("was refused by the shape mint"),
                    "the child died without the refusal message: {stderr}"
                );
            }
        }
        Ok(i) => {
            let bad = BAD[i.parse::<usize>().unwrap_or(0)];
            seed(bad, &["lt4b_q", &format!("lt4b_{bad:x}")]);
        }
    }
}

#[test]
fn the_counter_never_mints_into_the_static_band() {
    let keys = unsafe { canonical_keys_for_names(&[b"lt4c_only"]) };
    let id = shapes::shape_id_for_keys_ensure(keys.arr(), 1);
    assert!(is_shape_id(id) && id >= STATIC_SHAPE_ID_END, "{id:#x}");
}

#[test]
fn a_class_seed_takes_the_class_prototype_identity() {
    const SEEDED_CLASS_ID: u32 = 0x0074_1c11;
    let packed = b"lt4k_a\0lt4k_b\0";
    let keys =
        crate::object::js_build_class_keys_array(SEEDED_CLASS_ID, 2, packed.as_ptr(), 14) as u64;
    let requested = SHAPE_ID_BASE + 0x3456;
    let id = js_object_shape_id_for_class_keys_static(keys, 2, 2, SEEDED_CLASS_ID, requested);
    let record = shapes::shape_descriptor_by_id(id).expect("seeded record");
    assert_eq!(record.proto_id, shapes::class_proto_id(SEEDED_CLASS_ID));
    // Registration is idempotent: a second registration (another module
    // importing the class) resolves to the same id.
    assert_eq!(
        js_object_shape_id_for_class_keys_static(keys, 2, 2, SEEDED_CLASS_ID, requested),
        id
    );
    assert!(is_carrier(id));
}
